### ISSUE TITLE
Minimal running setup

### ISSUE THREAD

**Issue by bjornborg** [samtuhka/webtrajsim#2]
Hi,
I am studying the multiple papers referring to this repository.

I've been trying to configuring and building in order to get a running example without success (with minimal javascript and npm knowledge, npm installation of dependencies seems to be broken I think). Are there any tutorials or steps to get this up and running?

**Comment by bjornborg** [comment]
From what I've been able to deduct is that you use npm package management, chrome as a browser for displaying graphics and websocket for parsing data.

I've been modifying launch.sh to replace chrome with chromium and installing dependencies with ```npm install```

**Comment by samtuhka** [comment]
Newer versions of one of the dependencies appears to be break something. At package.json try changing `"bluebird": "^3.0.5" `to `"bluebird": "3.0.5" `and run `npm install` again. Also, you might have to enable third-party cookies on your browser to make it work.

**Comment by bjornborg** [comment]
With your proposed changes, I still get problems when loading the index.html.
Looking at the browser console: 
`Failed to load resource: net::ERR_FILE_NOT_FOUND in file:///home/bjornborg/git/webtrajsim/node_modules/system-npmlocator/node_modules/browser-builtins/package.json`

Furthermore in the linux termal I get:
`[16468:16468:1120/135823.802276:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.`

**Comment by samtuhka** [comment]
Hmm... Maybe a file-access issue with Chrome. 

Try running following from terminal (it will run it from a local server instead):
`python -m SimpleHTTPServer &  google-chrome "0.0.0.0:8000?experiment=fixSwitch&disableDefaultLogger=true"`

**Comment by bjornborg** [comment]
Hosting the http server and accessing it yields:
`python -m SimpleHTTPServer             
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [20/Nov/2019 15:39:32] code 404, message File not found
127.0.0.1 - - [20/Nov/2019 15:39:32] "GET /node_modules/system-npmlocator/node_modules/browser-builtins/package.json HTTP/1.1" 404 -
127.0.0.1 - - [20/Nov/2019 15:39:46] "GET /node_modules/system-npmlocator/npmlocator.js.map HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2019 15:39:46] "GET /vendor/bootstrap/css/bootstrap.css.map HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2019 15:40:05] code 404, message File not found
127.0.0.1 - - [20/Nov/2019 15:40:05] "GET /node_modules/system-npmlocator/node_modules/browser-builtins/package.json HTTP/1.1" 404 -
127.0.0.1 - - [20/Nov/2019 15:40:05] code 404, message File not found
127.0.0.1 - - [20/Nov/2019 15:40:05] "GET /favicon.ico HTTP/1.1" 404 -
`

and a black screen in chromium.

I also observe several errors in the webbrowser console

**Comment by samtuhka** [comment]
Unfortunately, I'm not able to replicate that. Here's the step-by-step that I'm following:

`git clone -b fixswitchsim https://github.com/samtuhka/webtrajsim`
`cd webtrajsim`
`npm install`
`python -m SimpleHTTPServer & google-chrome "0.0.0.0:8000?experiment=fixSwitch&disableDefaultLogger=true"'`

**Comment by bjornborg** [comment]
What python version are using, installed python modules?
google-chrome could be replaced with chromium, right?

**Comment by samtuhka** [comment]
~~Any python version should work (tested with 3.6 and 2.7)~~ Chromium should work as well, the original experiments were run on chromium if I remember correctly. 

Edit: I am incorrect. It's http.server in python3, not SimpleHTTPServer

**Comment by bjornborg** [comment]
Hosting the http server seems fine. I've tested both firefox and chromium in snap confinement without success. I also tested chromium natively deployed through apt as well, no success.

`chromium-browser "0.0.0.0:8000?experiment=fixSwitch&disableDefaultLogger=true"`
`[26883:26883:1120/161038.547285:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.`
`[26883:26883:1120/161038.696079:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command`

**Comment by bjornborg** [comment]
Do you have explicit dependency on gfx cards? Asking this since I am running this off a laptop.

**Comment by bjornborg** [comment]
Still same problem switching to python3, 
`python3 -m http.server`

**Comment by samtuhka** [comment]
Can you run other WebGL applications? For example https://threejs.org/examples/#webgl_animation_cloth

**Comment by bjornborg** [comment]
Yes, both in firefox and chromium.

**Comment by samtuhka** [comment]
Hi, 

Can you get [this](https://samtuhka.github.io/?experiment=singleScenario&singleScenario=fixSwitch&hideRoad=1) to work (might take a few seconds to load)?

Getting a steering wheel and the data-logging to work with it might be a bit of a hassle but it should at least give an idea on what the setup was. The instructions are all in Finnish unfortunately.

**Comment by bjornborg** [comment]
That seems to work, space seems to accelerate the viewer.

**Comment by bjornborg** [comment]
What's the difference between the most recent commit in branch birch18 vs the one you just hosted?

**Comment by samtuhka** [comment]
The one I hosted should be the same setup (you should be able to run the whole experiment by replacing `experiment=singleScenario` with `experiment=fixSwitch` in the URL) as Experiment 2 in the "Humans Use Predictive Gaze Strategies to Target Waypoints for Steering" paper. The birch one is an (ongoing) continuation experiment with some further tweaks.
